# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd14c3e3e9f505736928de9255ffce37c3e449f7fc0cae1911773d12ff24e1312c89eddff476fbb556b848b678d4b556c6996d3647f5f0adf944dc59ff1094ba

test:
  secret_key_base: 7384fbabd678e55924dfca695d434d1e2755d7498457ce47052661a990ac4d1ba1c4b3cffa685d49e13f3d2b3b73bba40cb8996a48e752393b54fb275ab730a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
